export const SELECTORS = {
  searchForm: '#search-form',
  listControls: '#list-controls-form',
  searchResults: '#search-results',
  authorOptions: '#author-filter-options',
  allAuthors: '#all-author-names',
  resultCount: '#result-count',
  authorCheckboxContainers: '.author-checkbox-container',
  pagination: '#pagination',
  modal: '#modal',
  modalBackdrop: '#modal-backdrop',
  closeModal: '#close-modal',
  modalContainer: '#modal .modal-container',
  modalBody: '#modal-body',
}
