export const SELECTORS = {
  searchForm: '#search-form',
  listControls: '#list-controls-form',
  searchResults: '#search-results',
  authorOptions: '#author-filter-options',
  allAuthors: '#all-author-names',
  resultCount: '#result-count',
  authorCheckboxContainers: '.author-checkbox-container',
  pagination: '#pagination',
  modal: '#modal',
  modalControls: '#modal-controls',
  closeModal: '#close-modal',
  modalContent: '#modal-content',
  poemInfo: '#poem-info',
  poemContainer: '#poem-container',
}
